config/routes.rb
Rails.application.routes.draw do
  # static landingpage
  root to: 'static#home'

  # first screen a user sees after he is logged in
  get '/welcome', to: 'transaction#welcome', as: :user_root
  get '/money', to: 'transaction#new', as: :new_transaction
  post '/send', to: 'transaction#create', as: :transaction

  # static paths
  get '/terms', to: 'static#terms', as: :terms
  get '/imprint', to: 'static#imprint', as: :imprint
  get '/privacy', to: 'static#privacy', as: :privacy
  get '/faq', to: 'static#faq', as: :faq

  # auth related routes
  devise_for :users, path: 'auth', path_names: { sign_in: 'login', sign_out: 'logout', password: 'secret', confirmation: 'verification', unlock: 'unblock', registration: 'register', sign_up: 'cmon_let_me_in' }
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/transaction.rb
class Transaction < ApplicationRecord
  # default currency
  register_currency :usd
  monetize :amount_send_cents, with_model_currency: :currency_sender
  monetize :amount_received_cents, with_model_currency: :currency_reciever

  validates :sender, presence: true
  validates :reciever, presence: true
  validates :amount_send_cents, presence: true
  validates :amount_received_cents, presence: true
  validates :currency_sender, presence: true
  validates :currency_reciever, presence: true

  belongs_to :sender, class_name: "User"
  belongs_to :reciever, class_name: "User"

  # this is where we allow new currencies
  enum currencies: ["USD", "EUR", "GBP"]
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :name, presence: true
  validates_acceptance_of :terms, :allow_nil => false, :message => "not accepted", :on => :create

  after_create :grant_welcome_money

  # Returns an object holding each amount of each currency owned
  # {"USD"=>#<Money fractional:11900 currency:USD>, "EUR"=>#<Money fractional:0 currency:EUR>, "GBP"=>#<Money fractional:0 currency:GBP>}
  def bank_balance
    walletes = {}
    for t in Transaction.currencies.keys
      walletes[t] = Money.new(0, t)
    end

    for t in self.transactions
      if t.sender == self 
        # negative transaction
        walletes[t.currency_sender.upcase] -= t.amount_send
        if t.reciever == self
          walletes[t.currency_reciever.upcase] += t.amount_received
        end
      else
        # positive transaction
        walletes[t.currency_reciever.upcase] += t.amount_received
      end
    end

    return walletes
  end

  # Method that sends money to someone if it is posible
  # Returns true on success
  def send_money(receiver_id, amount_send_cents, currency_sender, currency_reciever)
    if self.able_to_make_transaction?(amount_send_cents, currency_sender)
      # create money object
      amount_received = Money.new(amount_send_cents, currency_sender)
      # check if we need to calc an exchange
      amount_received = amount_received.exchange_to(currency_reciever) 
      a = Transaction.create!(
        sender_id: self.id,
        reciever_id: receiver_id,
        amount_send_cents: amount_send_cents,
        currency_sender: currency_sender,
        amount_received_cents: amount_received.cents,
        currency_reciever: currency_reciever
      )

      return true
    else
      return false
    end
  end

  # helper method that transacts 1000 USD as a starting balance from the HQ account to every user who signs up
  def grant_welcome_money
    Transaction.create(
      sender: User.find(1),
      reciever: self,
      amount_send_cents: 10000,
      amount_received_cents: 10000,
      currency_sender: "usd",
      currency_reciever: "usd"
    )
  end

  # Helper method to check if a user is able to make a transaction with a given amount in a given currency
  def able_to_make_transaction?(amount, currency)
    amount = Money.new(amount, currency)
    balance = bank_balance[currency]
    return balance > 0 && amount <= balance
  end

  # query own transactions
  def transactions
    Transaction.where("sender_id = ? OR reciever_id = ?", self.id, self.id).distinct
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:terms, :name])
  end
end

app/controllers/static_controller.rb
class StaticController < ApplicationController

  def home
  end

  def imprint
  end

  def privacy
  end

  def terms
  end

  def faq
  end
end

app/controllers/transaction_controller.rb
class TransactionController < ApplicationController
  before_action :authenticate_user!
  before_action :balance, only: [:welcome, :new]

  def welcome
  end

  def new
    @transaction = Transaction.new
    @possible_receivers = User.all
  end

  def create
    amount_send_cents = transaction_params["amount_send_cents"].to_f * 100
    if !transaction_params["receiver"].empty? && 
       amount_send_cents > 0.0 && 
       current_user.send_money(
         transaction_params["receiver"],
         amount_send_cents,
         transaction_params["currency_sender"],
         transaction_params["currency_reciever"],
        )
      redirect_to user_root_path, notice: 'Transaction complete' 
    else
      redirect_to :new_transaction, notice: 'Transaction failed' 
    end
  end

  private
    def transaction_params
      params.permit(:receiver, :amount_send_cents, :currency_sender, :currency_reciever)
    end

    def balance
      @balance = current_user.bank_balance
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/transaction_helper.rb
module TransactionHelper
end

app/views/layouts/_footer.html.haml
%footer.pt-5.pb-5.border-top
  .container
    .row
      .col-6
        %p.my-0.mr-md-auto.navbar-brand.text-dark.text-uppercase Transfery
        %p.text-muted
          The service for sending money fast
          %br
          Made with ❤ in Berlin
        %small.d-block.mb-3.text-muted © 2018-2019
      .col-md
        %h5 Resources
        %ul.list-unstyled.text-small
          %li
            = link_to "F.A.Q.", faq_path, class: "text-muted", rel: "nofollow"
          %li
            %a.text-muted{:href => "#"} Help Center
      .col-md
        %h5 About
        %ul.list-unstyled.text-small
          %li
            = link_to "Terms of Service", terms_path, class: "text-muted", rel: "nofollow"
          %li
            = link_to "Privacy", privacy_path, class: "text-muted", rel: "nofollow"
          %li
            = link_to "Imprint", imprint_path, class: "text-muted", rel: "nofollow"

app/views/layouts/_navbar.html.haml
.border-bottom.shadow-sm.bg-white
  .container-fluid
    .d-flex.flex-column.flex-md-row.align-items-center.p-3.px-md-4
      %a.my-0.mr-md-auto.navbar-brand.text-dark.text-uppercase{:href => root_path} Transfery
      - if user_signed_in?
        = link_to "Dashboard", user_root_path, class: "btn btn-primary mr-2"
        = link_to "Log out", destroy_user_session_path, :method => :delete , class: "btn btn-outline-primary"
      - else
        = link_to "Login", new_user_session_path, class: "btn btn-outline-primary mr-2"
        = link_to "Sign up", new_user_registration_path, class: "btn btn-primary"

app/views/layouts/_notifications.html.haml
%div.d-flex.justify-content-center.align-items-center{"aria-atomic" => "true", "aria-live" => "assertive", :style => "position: absolute; top: 80px; right: 10px;"}
  - flash.each do |key, value|
    .toast.show{"aria-atomic" => "true", "aria-live" => "assertive", :role => "alert"}
      .toast-header
        %strong.mr-auto.pr-3 Transfery
        %small.text-muted Just now
        %button.ml-2.mb-1.close{"aria-label" => "Close", "data-dismiss" => "toast", :type => "button"}
          %span{"aria-hidden" => "true"} ×
      .toast-body
        = value

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Transfery
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
  %body
    = render "layouts/notifications"
    = render "layouts/navbar"
    = yield
    = render "layouts/footer"
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'

app/views/transaction/_balance.html.haml
.row
  .col-lg-12
    - if small
      %h1.h4.mt-3.text-center.mb-3 Send money from your wallets
    - else
      %h1.mt-5 Wallets
  
  - for c in @balance
    .col-4.mb-4
      .card
        .card-body.text-center
          - if small
            %p#improvements.mb-0{style: "line-height: 1; font-weight: bold;"}
              = c[1]
          - else
            %p#improvements.display-3.mb-0{style: "line-height: 1; font-weight: bold;"}
              = c[1]
          %p.mb-0.text-black-50
            = c[0]

app/views/transaction/new.html.haml
.container
  .row.justify-content-md-center.mb-5.mt-5
    .col.col-lg-6.mb-5.mt-5.pb-3.bg-light
      = render "transaction/balance", small: true
      = form_tag(transaction_path, :method => "post", id: "search-form", class: "form") do
        - if @transaction.errors.any?
          #error_explanation
            %h2= "#{pluralize(@transaction.errors.count, "error")} prohibited this transaction from being saved:"
            %ul
              - @transaction.errors.full_messages.each do |message|
                %li= message
        .form-group
          = label_tag 'amount_send_cents', 'Money'
          = number_field_tag "amount_send_cents", nil, min: 0, step: 0.01, class: "form-control"
        .form-group
          = label_tag 'currency_sender', 'From currency wallet'
          = select_tag :currency_sender, options_for_select(Transaction.currencies.keys.to_a), class: "form-control"
        .form-group
          = label_tag 'receiver', 'Send to a friend'
          = select_tag "receiver", options_from_collection_for_select(@possible_receivers, "id", "name", "0"), include_blank: true, class: "custom-select"
        .form-group
          = label_tag 'currency_reciever', 'In currency'
          = select_tag :currency_reciever, options_for_select(Transaction.currencies.keys.to_a), class: "form-control"

        = submit_tag "Send money", class: "btn btn-danger btn-block"

app/views/transaction/welcome.html.haml
.container
  = render "transaction/balance", small: false

  .row.mt-5
    .col-lg-10
      %h1  Transactions
    .col-lg-2
      = link_to 'New Transaction', new_transaction_path, class: "btn btn-primary mt-2"

  %table.table
    %thead
      %tr
        %th ID
        %th From
        %th To
        %th Value
        %th Currency
        %th Created at
        %th Updated at

    %tbody
      - current_user.transactions.each do |t|
        / show two transactions if the user converted money from one wallet to another
        - if t.sender == t.reciever
          %tr
            %td= t.id
            %td= "You"
            %td= "You"
            %td.text-danger= "-#{t.amount_send}"
            %td= t.amount_send.currency
            %td= t.created_at.strftime("%B %d, %Y %I:%M")
            %td= t.updated_at.strftime("%B %d, %Y %I:%M")
          %tr
            %td= t.id
            %td= "You"
            %td= "You"
            %td.text-success= "+#{t.amount_received}"
            %td= t.amount_received.currency
            %td= t.created_at.strftime("%B %d, %Y %I:%M")
            %td= t.updated_at.strftime("%B %d, %Y %I:%M")
        - else
          %tr
            %td= t.id
            %td= t.sender.name
            - if t.reciever == current_user
              %td= "You"
              %td.text-success= "+#{t.amount_received}"
              %td= t.amount_received.currency
            - else
              %td= t.reciever.name
              %td.text-danger= "-#{t.amount_send}"
              %td= t.amount_send.currency
            %td= t.created_at.strftime("%B %d, %Y %I:%M")
            %td= t.updated_at.strftime("%B %d, %Y %I:%M")